# Registers the SourceCapsule native messaging host for the CURRENT USER only.
# No administrator rights are needed: everything lands under HKCU.
#
#   powershell -ExecutionPolicy Bypass -File scripts\install-native-host.ps1
#   powershell -ExecutionPolicy Bypass -File scripts\install-native-host.ps1 -Uninstall

[CmdletBinding()]
param(
    [string]$ExtensionId = 'gaclgcfljpjojddiikddejenlnjaggie',
    [switch]$Uninstall
)

$ErrorActionPreference = 'Stop'

$hostName = 'com.wolfgang_aura.sourcecapsule'
$repoRoot = Split-Path -Parent $PSScriptRoot
$hostDir = Join-Path $repoRoot 'native-host'
$hostScript = Join-Path $hostDir 'sourcecapsule-host.mjs'
$hostCmd = Join-Path $hostDir 'sourcecapsule-host.cmd'
$manifestPath = Join-Path $hostDir "$hostName.json"

# Chrome, Edge, and Brave all read the same per-user layout under their own key.
$registryRoots = @(
    'HKCU:\Software\Google\Chrome\NativeMessagingHosts',
    'HKCU:\Software\Microsoft\Edge\NativeMessagingHosts',
    'HKCU:\Software\BraveSoftware\Brave-Browser\NativeMessagingHosts'
)

if ($Uninstall) {
    foreach ($root in $registryRoots) {
        $key = Join-Path $root $hostName
        if (Test-Path $key) {
            Remove-Item -Path $key -Recurse -Force
            Write-Host "Removed $key"
        }
    }
    if (Test-Path $manifestPath) {
        Remove-Item -Path $manifestPath -Force
        Write-Host "Removed $manifestPath"
    }
    Write-Host 'SourceCapsule native host unregistered.'
    exit 0
}

if (-not (Test-Path $hostScript)) {
    throw "Host script not found: $hostScript"
}

$node = (Get-Command node -ErrorAction SilentlyContinue)
if ($null -eq $node) {
    throw 'node was not found on PATH. Install Node 18+ and re-run.'
}
$nodeExe = $node.Source
Write-Host "Node: $nodeExe"

# The .cmd wrapper is what Chrome actually executes; bake in the resolved node path so
# the host does not depend on PATH being inherited from the browser process.
$wrapper = @"
@echo off
REM Generated by scripts\install-native-host.ps1 - do not edit by hand.
"$nodeExe" "%~dp0sourcecapsule-host.mjs" %*
"@
Set-Content -Path $hostCmd -Value $wrapper -Encoding ascii
Write-Host "Wrote $hostCmd"

$manifest = [ordered]@{
    name           = $hostName
    description    = 'SourceCapsule local automation bridge'
    path           = $hostCmd
    type           = 'stdio'
    allowed_origins = @("chrome-extension://$ExtensionId/")
}
$manifest | ConvertTo-Json -Depth 4 | Set-Content -Path $manifestPath -Encoding utf8
Write-Host "Wrote $manifestPath"

foreach ($root in $registryRoots) {
    $key = Join-Path $root $hostName
    if (-not (Test-Path $key)) {
        New-Item -Path $key -Force | Out-Null
    }
    Set-ItemProperty -Path $key -Name '(Default)' -Value $manifestPath
    Write-Host "Registered $key"
}

Write-Host ''
Write-Host 'SourceCapsule native host registered for the current user.'
Write-Host "Extension ID expected: $ExtensionId"
Write-Host 'Reload the extension in chrome://extensions, then verify with:'
Write-Host '  node scripts\sourcecapsule-capture.mjs --ping'
